### ISSUE TITLE
Damage unit is missing from model created

### ISSUE THREAD

**Issue by Santonia27** [Deltares/hydromt_fiat#289]
**Current behavior**
the default currency for NSI data is in $. Currently there is no option to specify the currency in case of a model setup in a location outside the U.S

**Desired behavior**
The user can specify the currency in the settings.toml file 

**Tasks**
- [ ] Add option for the user to add currency in settings.toml file
- [ ] pull currency from settings.toml for output
- [ ] check OSM/JRC combination units
