### ISSUE TITLE
Census block groups geometries have same ids

### ISSUE THREAD

**Issue by panosatha** [Deltares/hydromt_fiat#349]
### hydomt_fiat version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of hydomt_fiat.

### Reproducible Example

I made a FIAT model for Maryland with the quick build option, and the resulting census block groups geometries had some areas that had the same id:
![image](https://github.com/user-attachments/assets/888a5584-71b1-4db4-a15d-df7bd676eaaa)

### Current behaviour

Something must go wrong when makingh the unique ids of the areas.

### Desired behaviour

Each census block group should have a unique id.

### Task list

- [x] Check where the creation of the id goes wrong
- [ ] Add a check for verifying that the ids are unique

**Comment by Santonia27** [comment]
The issue occurs during the spatial joint of the exposure gdf with the blockgroups as the blockgroups are a lot shorter in length than the exposure gdf. So I guess the closest points are assigned the same GEOID...

I'm not so familiar with the census data but is this GEOID assigned to each building or a small area? And if the latter, then shall we at a suffix to the duplicates?
