### ISSUE TITLE
Updating Exposure with roads throws error

### ISSUE THREAD

**Issue by Santonia27** [Deltares/hydromt_fiat#351]
### hydomt_fiat version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of hydomt_fiat.

### Reproducible Example

When creating a model in the MB GUI incl roads, the exposure cannot be updated (Finished Floor Height, Potential Damages) for the roads

### Current behaviour

![image](https://github.com/user-attachments/assets/8701c670-254f-4fb6-9111-68b51e96b42f)

### Desired behaviour

updating exposure incl roads without any problem

### Task list

- [ ] Fix bug by filtering out roads form gdf
