### ISSUE TITLE
Link to hydromt_fiat repo in docs issue template is broken

### ISSUE THREAD

**Issue by savente93** [Deltares/hydromt_fiat#357]
### hydomt_fiat version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of hydomt_fiat.

### Reproducible Example

goto new issue, choose documentation issue, click on the link where it says `I have checked that the issue still exists on the latest versions of the docs on main here *`.

### Current behaviour

 following the link will result in a 404 page

### Desired behaviour

The link should take the user to the place where they can check that the issue is still relevant 

### Task list

- [ ] decide where the link should go
- [ ] actually link there
