### ISSUE TITLE
hazard inconsistencies

### ISSUE THREAD

**Issue by panosatha** [Deltares/hydromt_fiat#366]
### hydomt_fiat version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of hydomt_fiat.

### Reproducible Example

Right now the hazard methods do not work consistenly between the main branch and the floodadapt branch. A generalized method should be used that then will allow merging floodadapt and main.

### Current behaviour

Right now the hazard methods do not work consistenly between the main branch and the floodadapt branch. A generalized method should be used that then will allow merging floodadapt and main.

### Desired behaviour

Right now the hazard methods do not work consistenly between the main branch and the floodadapt branch. A generalized method should be used that then will allow merging floodadapt and main.

### Task list

- [ ] change workflow in floodadapt branch
- [ ] test floodadapt use
- [ ] test generalized use
- [ ] merge to main
