### ISSUE TITLE
Two update_max_potential_damage functions

### ISSUE THREAD

**Issue by Santonia27** [Deltares/hydromt_fiat#367]
### hydomt_fiat version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of hydomt_fiat.

### Reproducible Example

When updating the pot. damages in the MB GUI, one functions is used and when running floodadapt or the test test_update_max_potential_damage in hydromt the oher functions is used.

### Current behaviour

There are 2 functions for update_max_potential_damage. The one called by the MB GUI is in fiat.py and the one called in floodadapt in the exposure_vector.

### Desired behaviour

only have one function

### Task list

- [ ] investigate the reason for 2 different functions
- [ ] investigate where which function is used in detail
- [ ] merge both functions to one and only use one
