### ISSUE TITLE
object indexing

### ISSUE THREAD

**Issue by panosatha** [Deltares/hydromt_fiat#368]
### hydomt_fiat version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of hydomt_fiat.

### Reproducible Example

It seems that for some of the methods with respect to applying changes (elevating, changing max damage etc.) the indexing was not implemented in a safe way, assuming that always exposure objects are in asceding order based on Object ID. Or reordering the objects.

Some of these parts were corrected in https://github.com/Deltares/hydromt_fiat/pull/365, but it is better to a general check of all these methods again to ensure that they are implemented correcty.

### Current behaviour

Check above

### Desired behaviour

Safe way of indexing FIAT objects.
The object ID should be always used for indexing since it is the unique identifier

### Task list

- [ ] go through all the methods using indexing and check implementation
- [ ] apply general object base indexing and not a different approach in every method ( the object ID should be always used for indexing since it is the unique identifier)

**Comment by Santonia27** [comment]
Can you please list which methods are used in Floodadapt;

- Elevate homes  = update_ground_floor_height?
(- Check update classification)

Anything else?

**Comment by Santonia27** [comment]
[inventory.docx](https://github.com/user-attachments/files/16609437/inventory.docx)
