### ISSUE TITLE
Docs upload workflow keeps crashing

### ISSUE THREAD

**Issue by Santonia27** [Deltares/hydromt_fiat#380]
### hydomt_fiat version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of hydomt_fiat.

### Reproducible Example

when trying to upload the docs the workflow cashes

### Current behaviour

when trying to upload the docs the workflow cashes

### Desired behaviour

smooth docs upload

### Task list

- [ ] indetify error
- [ ] update config workflow (if neccessary)

**Comment by Santonia27** [comment]
removed aggregration notebook temporarily until floodadapt branch is merged into main branch.
