### ISSUE TITLE
write_geoms assumes that there is always a region file

### ISSUE THREAD

**Issue by panosatha** [Deltares/hydromt_fiat#388]
### hydomt_fiat version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of hydomt_fiat.

### Reproducible Example

Reading a model without a region and then trying to write it, will produce an error.

### Current behaviour

The write_geoms methods assums that there is always a region gemetry and tries to clip the geometries based on that:
https://github.com/Deltares/hydromt_fiat/blob/f6932b3af30f49db641862e2a14afa802b317d3a/hydromt_fiat/fiat.py#L1331-L1337

### Desired behaviour

Sometimes FIAT models do not have a region, so there should be a check and only if there is a region. clip the geoms.

### Task list

- [x] Add check in method
- [x] Test with FloodAdapt
