### ISSUE TITLE
new composite area FFE not working as expected

### ISSUE THREAD

**Issue by panosatha** [Deltares/hydromt_fiat#394]
### hydomt_fiat version checks

- [x] I have checked that this issue has not already been reported.
- [x] I have checked that this bug exists on the latest version of hydomt_fiat.

### Reproducible Example

The way the FFE of the new composite areas is not as expected. If datum is selected, the elevation is immediatelly used as FFE. 

### Current behaviour

The way the FFE of the new composite areas is not as expected. If datum is selected, the elevation is immediatelly used as FFE. 

### Desired behaviour

A comparison to the ground elevation should be made. Same goes for base flood elevation as reference.

Allow for different heights per polygon as well!

### Task list

- [x] correct code for datum
- [x] correct code for base flood elevation
- [x] allow different height per polygon
- [x] check use
