### ISSUE TITLE
OSM download multipolygons

### ISSUE THREAD

**Issue by Santonia27** [Deltares/hydromt_fiat#396]
### hydomt_fiat version checks

- [x] I have checked that this issue has not already been reported.
- [x] I have checked that this bug exists on the latest version of hydomt_fiat.

### Reproducible Example

When downloading OSM exposure it is possible that some assets are downloaded as multipolygons e.g university buildings.

### Current behaviour

When downloading OSM exposure it is possible that some assets are downloaded as multipolygons e.g university buildings.

### Desired behaviour

Multipolygons should be extracted and assigned a new object ID

### Task list

- [ ] after OSM download check for multipolygons
- [ ] if present - explode and assign new Object ID
- [ ] update damages/gfh: remove code bit that filters out multipolygons
