### ISSUE TITLE
spliting new  composite areas uses max damage for indexing

### ISSUE THREAD

**Issue by panosatha** [Deltares/hydromt_fiat#407]
### hydomt_fiat version checks

- [x] I have checked that this issue has not already been reported.
- [x] I have checked that this bug exists on the latest version of hydomt_fiat.

### Reproducible Example

If you add multiple polygons for new composites areas that have the exact same area (which is bound to happen when you copy paste geometry features), the resulting geometries after splitting for aggregation areas, will be repeated multiple times, exploding the number of objects.

### Current behaviour

While doing the splitting of the new composite areas based on the aggregation areas outlines, there is a check that bases the identification of the polygons that were splitted to the max potential damage of hte intitial polygons:
https://github.com/Deltares/hydromt_fiat/blob/a2dcc5ef86d889b9cfef88b53b9bd70512c4e184/hydromt_fiat/workflows/aggregation_areas.py#L295

But if there are polygons with the exact same area, there are multiple objects that have the same max potential damage, thus exploding the number of objects when doing the indexing.

### Desired behaviour

The indexing should be done based on the initial unique ids and not the max potential damage.

### Task list

- [ ] Update code
- [ ] Test with examples from FloodAdapt
